name: toxic
description: Toxic density
version: 1.1.0
homepage: https://github.com/ArcaneArts/toxic
environment:
  sdk: '>=2.19.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: any
  rxdart: any
  provider: any
dev_dependencies:
  test: ^1.25.2
flutter: