name: toxic
description: Toxic density
version: 1.1.1
homepage: https://github.com/ArcaneArts/toxic
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: any
  rxdart: any
flutter: